server:
  port: ${8888}

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: https://auth-service-xwcs.onrender.com
              predicates:
                - Path=/auth,/auth/**

            - id: restaurant-service
              uri: https://restaurant-service-ofy0.onrender.com
              predicates:
                - Path=/restaurants,/restaurants/**

            - id: order-service
              uri: https://order-service-0z4f.onrender.com
              predicates:
                - Path=/orders,/orders/**

            - id: payment-service
              uri: https://payment-service-61hu.onrender.com
              predicates:
                - Path=/payments,/payments/**